version: '3.9'
services:
  springboot-app:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Use the Dockerfile in the current directory
    ports:
      - "9001:9001"  # Map your Spring Boot app's port to the host
    depends_on:
      - elasticsearch
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/your_db_name
      SPRING_DATASOURCE_USERNAME: your_db_username
      SPRING_DATASOURCE_PASSWORD: your_db_password
      SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES: http://elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    ports:
      - "9200:9200"  # Expose Elasticsearch HTTP API port
      - "9300:9300"  # Expose Elasticsearch transport port
    environment:
      - "discovery.type=single-node"  # Run Elasticsearch as a single node
      - "cluster.name=my-custom-cluster"  # Specify a custom cluster name
      - "xpack.security.enabled=false"  # Disable security
#      - "xpack.security.user=your-username:your-password"
    tty: true

  postgres:
    image: postgres:13
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_username
      POSTGRES_PASSWORD: your_db_password
