# logging
logging:
  level:
    '[com.backend.java]': TRACE
    org.springframework.data.elasticsearch.client.WIRE: TRACE

# configuration
app:
  timezone: Asia/Jakarta
credential:
  APIkey: ${SECRET_KEY}

# database source
spring:
  main:
    allow-circular-references: true
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    data:
      elasticsearch:
        cluster-nodes: ${ELASTICSEARCH_NODES_URL}
        cluster-name: ${ELASTICSEARCH_CLUSTER_NAME}
        repositories:
          enabled: true

# identify server port running on default environment
server:
  port: ${PORT}

elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  port: ${ELASTICSEARCH_PORT}
