# logging
logging:
  level:
    '[com.backend.java]': TRACE
    org.springframework.data.elasticsearch.client.WIRE: TRACE

# configuration
app:
  timezone: Asia/Jakarta
credential:
  APIkey: ${SECRET_KEY}

# database source
spring:
  main:
    allow-circular-references: true
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  elasticsearch:
    uris: [${ELASTICSEARCH_NODES_URL}]
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    data:
      elasticsearch:
        repositories:
          enabled: true
